In [18]:
import pymysql
import requests
import json

###　下載分析pm2.5 opendata資料

In [19]:
url="https://data.moenv.gov.tw/api/v2/aqx_p_02?api_key=af57253c-e838-46da-a1f5-12b43afd75f3&limit=1000&sort=datacreationdate%20desc&format=JSON"

In [20]:
headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
    }
res=requests.get(url,headers=headers,verify=False)
res

c:\Users\roger\Desktop\Django-陳岳洋\5.MYSQL\pm25_tomysql複習2\.venv\Lib\site-packages\urllib3\connectionpool.py:1097: InsecureRequestWarning: Unverified HTTPS request is being made to host 'data.moenv.gov.tw'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
  warnings.warn(

In [22]:
datas=res.json()

In [23]:
len(datas)

1000

In [24]:
datas[0]

{'site': '林森',
 'county': '臺南市',
 'pm25': '24',
 'datacreationdate': '2026-04-21 03:00',
 'itemunit': 'μg/m3'}

### 建立資料表

In [10]:
table_str="""
create table if not exists pm25(
    id int auto_increment primary key,
    site varchar(25),
    county varchar(25),
    pm25 int,
    datacreationdate datetime,
    itemunit varchar(20),
    unique key site_time (site, datacreationdate)
)
"""

### 連接資料庫

In [25]:
conn = pymysql.connect(
    host="mysql-3650ed2-pm25.e.aivencloud.com",
    user="avnadmin",
    passwd="AVNS_-hDOnmEfwqkcZfFy7WF",
    port=21697,
    db="defaultdb",
)

# conn = pymysql.connect(
#     host="127.0.0.1",
#     user="root",
#     passwd="",
#     port=3307,
#     db="demo",
# )
cursor=conn.cursor()
cursor

In [11]:
cursor.execute(table_str)
conn.commit()

### 寫入一筆資料

In [12]:
sqlstr="insert into pm25(site,county,pm25,datacreationdate,itemunit)\
 values('{}', '{}', '{}', '{}', '{}')"
data=list(datas[0].values())
print(data)
sqlstr.format(data[0]  ,data[1]  ,data[2]  ,data[3]  ,data[4]  )

['林森', '臺南市', '20', '2026-04-12 00:00', 'μg/m3']

"insert into pm25(site,county,pm25,datacreationdate,itemunit) values('林森', '臺南市', '20', '2026-04-12 00:00', 'μg/m3')"

In [13]:
cursor.execute(sqlstr.format(data[0]  ,data[1]  ,data[2]  ,data[3]  ,data[4]  ))
conn.commit()

### 一次寫入
- 加上 ignore

In [15]:
sqlstr="insert ignore into pm25(site,county,pm25,datacreationdate,itemunit)\
 values(%s, %s, %s, %s, %s)"

# 移除pm25空字串部分
values=[list(data.values()) for data in datas if list(data.values())[2]!=""]

cursor.executemany(sqlstr,values)
conn.commit()

In [16]:
conn.close()

In [16]:
import pandas as pd

In [36]:
cursor.execute("select * from pm25")

datas=cursor.fetchall()
datas

((1, '林森', '臺南市', 20, datetime.datetime(2026, 4, 12, 0, 0), 'μg/m3'),
 (2, '員林', '彰化縣', 21, datetime.datetime(2026, 4, 12, 0, 0), 'μg/m3'),
 (3, '臺灣大道', '臺中市', 23, datetime.datetime(2026, 4, 12, 0, 0), 'μg/m3'),
 (4, '大城', '彰化縣', 23, datetime.datetime(2026, 4, 12, 0, 0), 'μg/m3'),
 (5, '富貴角', '新北市', 16, datetime.datetime(2026, 4, 12, 0, 0), 'μg/m3'),
 (6, '麥寮', '雲林縣', 23, datetime.datetime(2026, 4, 12, 0, 0), 'μg/m3'),
 (7, '關山', '臺東縣', 17, datetime.datetime(2026, 4, 12, 0, 0), 'μg/m3'),
 (8, '金門', '金門縣', 13, datetime.datetime(2026, 4, 12, 0, 0), 'μg/m3'),
 (9, '馬祖', '連江縣', 17, datetime.datetime(2026, 4, 12, 0, 0), 'μg/m3'),
 (10, '埔里', '南投縣', 23, datetime.datetime(2026, 4, 12, 0, 0), 'μg/m3'),
 (11, '復興', '高雄市', 17, datetime.datetime(2026, 4, 12, 0, 0), 'μg/m3'),
 (12, '永和', '新北市', 21, datetime.datetime(2026, 4, 12, 0, 0), 'μg/m3'),
 (13, '竹山', '南投縣', 19, datetime.datetime(2026, 4, 12, 0, 0), 'μg/m3'),
 (14, '中壢', '桃園市', 21, datetime.datetime(2026, 4, 12, 0, 0), 'μg/m3'),
 (15, '三重', '新北市', 19, datetime.datetime(2026, 4, 12, 0, 0), 'μg/m3'),
 (16, '冬山', '宜蘭縣', 22, datetime.datetime(2026, 4, 12, 0, 0), 'μg/m3'),
 (17, '宜蘭', '宜蘭縣', 17, datetime.datetime(2026, 4, 12, 0, 0), 'μg/m3'),
 (18, '陽明', '臺北市', 22, datetime.datetime(2026, 4, 12, 0, 0), 'μg/m3'),
 (19, '花蓮', '花蓮縣', 23, datetime.datetime(2026, 4, 12, 0, 0), 'μg/m3'),
 (20, '臺東', '臺東縣', 22, datetime.datetime(2026, 4, 12, 0, 0), 'μg/m3'),
 (21, '恆春', '屏東縣', 16, datetime.datetime(2026, 4, 12, 0, 0), 'μg/m3'),
 (22, '潮州', '屏東縣', 15, datetime.datetime(2026, 4, 12, 0, 0), 'μg/m3'),
 (23, '屏東', '屏東縣', 24, datetime.datetime(2026, 4, 12, 0, 0), 'μg/m3'),
 (24, '小港', '高雄市', 25, datetime.datetime(2026, 4, 12, 0, 0), 'μg/m3'),
 (25, '前鎮', '高雄市', 17, datetime.datetime(2026, 4, 12, 0, 0), 'μg/m3'),
 (26, '前金', '高雄市', 15, datetime.datetime(2026, 4, 12, 0, 0), 'μg/m3'),
 (27, '左營', '高雄市', 21, datetime.datetime(2026, 4, 12, 0, 0), 'μg/m3'),
 (28, '楠梓', '高雄市', 23, datetime.datetime(2026, 4, 12, 0, 0), 'μg/m3'),
 (29, '林園', '高雄市', 21, datetime.datetime(2026, 4, 12, 0, 0), 'μg/m3'),
 (30, '大寮', '高雄市', 30, datetime.datetime(2026, 4, 12, 0, 0), 'μg/m3'),
 (31, '鳳山', '高雄市', 20, datetime.datetime(2026, 4, 12, 0, 0), 'μg/m3'),
 (32, '仁武', '高雄市', 19, datetime.datetime(2026, 4, 12, 0, 0), 'μg/m3'),
 (33, '橋頭', '高雄市', 24, datetime.datetime(2026, 4, 12, 0, 0), 'μg/m3'),
 (34, '美濃', '高雄市', 23, datetime.datetime(2026, 4, 12, 0, 0), 'μg/m3'),
 (35, '臺南', '臺南市', 23, datetime.datetime(2026, 4, 12, 0, 0), 'μg/m3'),
 (36, '安南', '臺南市', 21, datetime.datetime(2026, 4, 12, 0, 0), 'μg/m3'),
 (37, '善化', '臺南市', 25, datetime.datetime(2026, 4, 12, 0, 0), 'μg/m3'),
 (38, '新營', '臺南市', 22, datetime.datetime(2026, 4, 12, 0, 0), 'μg/m3'),
 (39, '嘉義', '嘉義市', 21, datetime.datetime(2026, 4, 12, 0, 0), 'μg/m3'),
 (40, '臺西', '雲林縣', 19, datetime.datetime(2026, 4, 12, 0, 0), 'μg/m3'),
 (41, '朴子', '嘉義縣', 20, datetime.datetime(2026, 4, 12, 0, 0), 'μg/m3'),
 (42, '新港', '嘉義縣', 24, datetime.datetime(2026, 4, 12, 0, 0), 'μg/m3'),
 (43, '崙背', '雲林縣', 19, datetime.datetime(2026, 4, 12, 0, 0), 'μg/m3'),
 (44, '斗六', '雲林縣', 22, datetime.datetime(2026, 4, 12, 0, 0), 'μg/m3'),
 (45, '南投', '南投縣', 19, datetime.datetime(2026, 4, 12, 0, 0), 'μg/m3'),
 (46, '二林', '彰化縣', 22, datetime.datetime(2026, 4, 12, 0, 0), 'μg/m3'),
 (47, '線西', '彰化縣', 26, datetime.datetime(2026, 4, 12, 0, 0), 'μg/m3'),
 (48, '彰化', '彰化縣', 20, datetime.datetime(2026, 4, 12, 0, 0), 'μg/m3'),
 (49, '西屯', '臺中市', 20, datetime.datetime(2026, 4, 12, 0, 0), 'μg/m3'),
 (50, '忠明', '臺中市', 21, datetime.datetime(2026, 4, 12, 0, 0), 'μg/m3'),
 (51, '大里', '臺中市', 19, datetime.datetime(2026, 4, 12, 0, 0), 'μg/m3'),
 (52, '沙鹿', '臺中市', 22, datetime.datetime(2026, 4, 12, 0, 0), 'μg/m3'),
 (53, '豐原', '臺中市', 18, datetime.datetime(2026, 4, 12, 0, 0), 'μg/m3'),
 (54, '三義', '苗栗縣', 18, datetime.datetime(2026, 4, 12, 0, 0), 'μg/m3'),
 (55, '苗栗', '苗栗縣', 25, datetime.datetime(2026, 4, 12, 0, 0), 'μg/m3'),
 (56, '頭份', '苗栗縣', 24, datetime.datetime(2026, 4, 12, 0, 0), 'μg/m3'),
 (57, '新竹', '新竹市', 21, datetime.datetime(2026, 4, 12, 0, 0), 'μg/m3'),
 (58, '竹東', '新竹縣', 22, datetime.datetime(2026, 4, 12, 0, 0), 'μg/m3'),
 (59, '湖口', '新竹縣', 19, datetime.datetime(2026, 4, 12, 0, 0), 'μg/m3'),
 (60, '龍潭', '桃園市', 24, datetime.datetime(2026, 4, 12, 0, 0), 'μg/m3'),
 (61, '平鎮', '桃園市', 18, datetime.datetime(2026, 4, 12, 0, 0), 'μg/m3'),
 (62, '觀音', '桃園市', 19, datetime.datetime(2026, 4, 12, 0, 0), 'μg/m3'),
 (63, '大園', '桃園市', 24, datetime.datetime(2026, 4, 12, 0, 0), 'μg/m3'),
 (64, '桃園', '桃園市', 22, datetime.datetime(2026, 4, 12, 0, 0), 'μg/m3'),
 (65, '大同', '臺北市', 19, datetime.datetime(2026, 4, 12, 0, 0), 'μg/m3'),
 (66, '松山', '臺北市', 22, datetime.datetime(2026, 4, 12, 0, 0), 'μg/m3'),
 (67, '古亭', '臺北市', 20, datetime.datetime(2026, 4, 12, 0, 0), 'μg/m3'),
 (68, '萬華', '臺北市', 19, datetime.datetime(2026, 4, 12, 0, 0), 'μg/m3'),
 (69, '中山', '臺北市', 18, datetime.datetime(2026, 4, 12, 0, 0), 'μg/m3'),
 (70, '士林', '臺北市', 18, datetime.datetime(2026, 4, 12, 0, 0), 'μg/m3'),
 (71, '淡水', '新北市', 23, datetime.datetime(2026, 4, 12, 0, 0), 'μg/m3'),
 (72, '林口', '新北市', 23, datetime.datetime(2026, 4, 12, 0, 0), 'μg/m3'),
 (73, '菜寮', '新北市', 21, datetime.datetime(2026, 4, 12, 0, 0), 'μg/m3'),
 (74, '新莊', '新北市', 21, datetime.datetime(2026, 4, 12, 0, 0), 'μg/m3'),
 (75, '板橋', '新北市', 20, datetime.datetime(2026, 4, 12, 0, 0), 'μg/m3'),
 (76, '土城', '新北市', 20, datetime.datetime(2026, 4, 12, 0, 0), 'μg/m3'),
 (77, '新店', '新北市', 25, datetime.datetime(2026, 4, 12, 0, 0), 'μg/m3'),
 (78, '汐止', '新北市', 19, datetime.datetime(2026, 4, 12, 0, 0), 'μg/m3'),
 (79, '基隆', '基隆市', 19, datetime.datetime(2026, 4, 12, 0, 0), 'μg/m3'),
 (80, '林森', '臺南市', 19, datetime.datetime(2026, 4, 11, 23, 0), 'μg/m3'),
 (81, '員林', '彰化縣', 21, datetime.datetime(2026, 4, 11, 23, 0), 'μg/m3'),
 (82, '臺灣大道', '臺中市', 23, datetime.datetime(2026, 4, 11, 23, 0), 'μg/m3'),
 (83, '大城', '彰化縣', 25, datetime.datetime(2026, 4, 11, 23, 0), 'μg/m3'),
 (84, '富貴角', '新北市', 15, datetime.datetime(2026, 4, 11, 23, 0), 'μg/m3'),
 (85, '麥寮', '雲林縣', 21, datetime.datetime(2026, 4, 11, 23, 0), 'μg/m3'),
 (86, '關山', '臺東縣', 20, datetime.datetime(2026, 4, 11, 23, 0), 'μg/m3'),
 (87, '金門', '金門縣', 14, datetime.datetime(2026, 4, 11, 23, 0), 'μg/m3'),
 (88, '馬祖', '連江縣', 15, datetime.datetime(2026, 4, 11, 23, 0), 'μg/m3'),
 (89, '埔里', '南投縣', 23, datetime.datetime(2026, 4, 11, 23, 0), 'μg/m3'),
 (90, '復興', '高雄市', 19, datetime.datetime(2026, 4, 11, 23, 0), 'μg/m3'),
 (91, '永和', '新北市', 18, datetime.datetime(2026, 4, 11, 23, 0), 'μg/m3'),
 (92, '竹山', '南投縣', 18, datetime.datetime(2026, 4, 11, 23, 0), 'μg/m3'),
 (93, '中壢', '桃園市', 28, datetime.datetime(2026, 4, 11, 23, 0), 'μg/m3'),
 (94, '三重', '新北市', 24, datetime.datetime(2026, 4, 11, 23, 0), 'μg/m3'),
 (95, '冬山', '宜蘭縣', 18, datetime.datetime(2026, 4, 11, 23, 0), 'μg/m3'),
 (96, '宜蘭', '宜蘭縣', 17, datetime.datetime(2026, 4, 11, 23, 0), 'μg/m3'),
 (97, '陽明', '臺北市', 18, datetime.datetime(2026, 4, 11, 23, 0), 'μg/m3'),
 (98, '花蓮', '花蓮縣', 23, datetime.datetime(2026, 4, 11, 23, 0), 'μg/m3'),
 (99, '臺東', '臺東縣', 23, datetime.datetime(2026, 4, 11, 23, 0), 'μg/m3'),
 (100, '恆春', '屏東縣', 18, datetime.datetime(2026, 4, 11, 23, 0), 'μg/m3'),
 (101, '潮州', '屏東縣', 20, datetime.datetime(2026, 4, 11, 23, 0), 'μg/m3'),
 (102, '屏東', '屏東縣', 19, datetime.datetime(2026, 4, 11, 23, 0), 'μg/m3'),
 (103, '小港', '高雄市', 20, datetime.datetime(2026, 4, 11, 23, 0), 'μg/m3'),
 (104, '前鎮', '高雄市', 17, datetime.datetime(2026, 4, 11, 23, 0), 'μg/m3'),
 (105, '前金', '高雄市', 20, datetime.datetime(2026, 4, 11, 23, 0), 'μg/m3'),
 (106, '左營', '高雄市', 20, datetime.datetime(2026, 4, 11, 23, 0), 'μg/m3'),
 (107, '楠梓', '高雄市', 16, datetime.datetime(2026, 4, 11, 23, 0), 'μg/m3'),
 (108, '林園', '高雄市', 18, datetime.datetime(2026, 4, 11, 23, 0), 'μg/m3'),
 (109, '大寮', '高雄市', 30, datetime.datetime(2026, 4, 11, 23, 0), 'μg/m3'),
 (110, '鳳山', '高雄市', 20, datetime.datetime(2026, 4, 11, 23, 0), 'μg/m3'),
 (111, '仁武', '高雄市', 17, datetime.datetime(2026, 4, 11, 23, 0), 'μg/m3'),
 (112, '橋頭', '高雄市', 23, datetime.datetime(2026, 4, 11, 23, 0), 'μg/m3'),
 (113, '美濃', '高雄市', 21, datetime.datetime(2026, 4, 11, 23, 0), 'μg/m3'),
 (114, '臺南', '臺南市', 20, datetime.datetime(2026, 4, 11, 23, 0), 'μg/m3'),
 (115, '安南', '臺南市', 21, datetime.datetime(2026, 4, 11, 23, 0), 'μg/m3'),
 (116, '善化', '臺南市', 25, datetime.datetime(2026, 4, 11, 23, 0), 'μg/m3'),
 (117, '新營', '臺南市', 27, datetime.datetime(2026, 4, 11, 23, 0), 'μg/m3'),
 (118, '嘉義', '嘉義市', 21, datetime.datetime(2026, 4, 11, 23, 0), 'μg/m3'),
 (119, '臺西', '雲林縣', 20, datetime.datetime(2026, 4, 11, 23, 0), 'μg/m3'),
 (120, '朴子', '嘉義縣', 17, datetime.datetime(2026, 4, 11, 23, 0), 'μg/m3'),
 (121, '新港', '嘉義縣', 20, datetime.datetime(2026, 4, 11, 23, 0), 'μg/m3'),
 (122, '崙背', '雲林縣', 25, datetime.datetime(2026, 4, 11, 23, 0), 'μg/m3'),
 (123, '斗六', '雲林縣', 21, datetime.datetime(2026, 4, 11, 23, 0), 'μg/m3'),
 (124, '南投', '南投縣', 24, datetime.datetime(2026, 4, 11, 23, 0), 'μg/m3'),
 (125, '二林', '彰化縣', 19, datetime.datetime(2026, 4, 11, 23, 0), 'μg/m3'),
 (126, '線西', '彰化縣', 26, datetime.datetime(2026, 4, 11, 23, 0), 'μg/m3'),
 (127, '彰化', '彰化縣', 19, datetime.datetime(2026, 4, 11, 23, 0), 'μg/m3'),
 (128, '西屯', '臺中市', 21, datetime.datetime(2026, 4, 11, 23, 0), 'μg/m3'),
 (129, '忠明', '臺中市', 20, datetime.datetime(2026, 4, 11, 23, 0), 'μg/m3'),
 (130, '大里', '臺中市', 22, datetime.datetime(2026, 4, 11, 23, 0), 'μg/m3'),
 (131, '沙鹿', '臺中市', 21, datetime.datetime(2026, 4, 11, 23, 0), 'μg/m3'),
 (132, '豐原', '臺中市', 20, datetime.datetime(2026, 4, 11, 23, 0), 'μg/m3'),
 (133, '三義', '苗栗縣', 24, datetime.datetime(2026, 4, 11, 23, 0), 'μg/m3'),
 (134, '苗栗', '苗栗縣', 27, datetime.datetime(2026, 4, 11, 23, 0), 'μg/m3'),
 (135, '頭份', '苗栗縣', 21, datetime.datetime(2026, 4, 11, 23, 0), 'μg/m3'),
 (136, '新竹', '新竹市', 15, datetime.datetime(2026, 4, 11, 23, 0), 'μg/m3'),
 (137, '竹東', '新竹縣', 24, datetime.datetime(2026, 4, 11, 23, 0), 'μg/m3'),
 (138, '湖口', '新竹縣', 16, datetime.datetime(2026, 4, 11, 23, 0), 'μg/m3'),
 (139, '龍潭', '桃園市', 21, datetime.datetime(2026, 4, 11, 23, 0), 'μg/m3'),
 (140, '平鎮', '桃園市', 25, datetime.datetime(2026, 4, 11, 23, 0), 'μg/m3'),
 (141, '觀音', '桃園市', 19, datetime.datetime(2026, 4, 11, 23, 0), 'μg/m3'),
 (142, '大園', '桃園市', 17, datetime.datetime(2026, 4, 11, 23, 0), 'μg/m3'),
 (143, '桃園', '桃園市', 20, datetime.datetime(2026, 4, 11, 23, 0), 'μg/m3'),
 (144, '大同', '臺北市', 25, datetime.datetime(2026, 4, 11, 23, 0), 'μg/m3'),
 (145, '松山', '臺北市', 17, datetime.datetime(2026, 4, 11, 23, 0), 'μg/m3'),
 (146, '古亭', '臺北市', 14, datetime.datetime(2026, 4, 11, 23, 0), 'μg/m3'),
 (147, '萬華', '臺北市', 19, datetime.datetime(2026, 4, 11, 23, 0), 'μg/m3'),
 (148, '中山', '臺北市', 24, datetime.datetime(2026, 4, 11, 23, 0), 'μg/m3'),
 (149, '士林', '臺北市', 21, datetime.datetime(2026, 4, 11, 23, 0), 'μg/m3'),
 (150, '淡水', '新北市', 21, datetime.datetime(2026, 4, 11, 23, 0), 'μg/m3'),
 (151, '林口', '新北市', 19, datetime.datetime(2026, 4, 11, 23, 0), 'μg/m3'),
 (152, '菜寮', '新北市', 20, datetime.datetime(2026, 4, 11, 23, 0), 'μg/m3'),
 (153, '新莊', '新北市', 21, datetime.datetime(2026, 4, 11, 23, 0), 'μg/m3'),
 (154, '板橋', '新北市', 26, datetime.datetime(2026, 4, 11, 23, 0), 'μg/m3'),
 (155, '土城', '新北市', 18, datetime.datetime(2026, 4, 11, 23, 0), 'μg/m3'),
 (156, '新店', '新北市', 25, datetime.datetime(2026, 4, 11, 23, 0), 'μg/m3'),
 (157, '汐止', '新北市', 23, datetime.datetime(2026, 4, 11, 23, 0), 'μg/m3'),
 (158, '基隆', '基隆市', 20, datetime.datetime(2026, 4, 11, 23, 0), 'μg/m3'),
 (159, '林森', '臺南市', 18, datetime.datetime(2026, 4, 11, 22, 0), 'μg/m3'),
 (160, '員林', '彰化縣', 22, datetime.datetime(2026, 4, 11, 22, 0), 'μg/m3'),
 (161, '臺灣大道', '臺中市', 21, datetime.datetime(2026, 4, 11, 22, 0), 'μg/m3'),
 (162, '大城', '彰化縣', 21, datetime.datetime(2026, 4, 11, 22, 0), 'μg/m3'),
 (163, '富貴角', '新北市', 17, datetime.datetime(2026, 4, 11, 22, 0), 'μg/m3'),
 (164, '麥寮', '雲林縣', 18, datetime.datetime(2026, 4, 11, 22, 0), 'μg/m3'),
 (165, '關山', '臺東縣', 21, datetime.datetime(2026, 4, 11, 22, 0), 'μg/m3'),
 (166, '金門', '金門縣', 13, datetime.datetime(2026, 4, 11, 22, 0), 'μg/m3'),
 (167, '馬祖', '連江縣', 21, datetime.datetime(2026, 4, 11, 22, 0), 'μg/m3'),
 (168, '埔里', '南投縣', 20, datetime.datetime(2026, 4, 11, 22, 0), 'μg/m3'),
 (169, '復興', '高雄市', 17, datetime.datetime(2026, 4, 11, 22, 0), 'μg/m3'),
 (170, '永和', '新北市', 24, datetime.datetime(2026, 4, 11, 22, 0), 'μg/m3'),
 (171, '竹山', '南投縣', 20, datetime.datetime(2026, 4, 11, 22, 0), 'μg/m3'),
 (172, '中壢', '桃園市', 24, datetime.datetime(2026, 4, 11, 22, 0), 'μg/m3'),
 (173, '三重', '新北市', 20, datetime.datetime(2026, 4, 11, 22, 0), 'μg/m3'),
 (174, '冬山', '宜蘭縣', 20, datetime.datetime(2026, 4, 11, 22, 0), 'μg/m3'),
 (175, '宜蘭', '宜蘭縣', 14, datetime.datetime(2026, 4, 11, 22, 0), 'μg/m3'),
 (176, '陽明', '臺北市', 24, datetime.datetime(2026, 4, 11, 22, 0), 'μg/m3'),
 (177, '花蓮', '花蓮縣', 18, datetime.datetime(2026, 4, 11, 22, 0), 'μg/m3'),
 (178, '臺東', '臺東縣', 19, datetime.datetime(2026, 4, 11, 22, 0), 'μg/m3'),
 (179, '恆春', '屏東縣', 17, datetime.datetime(2026, 4, 11, 22, 0), 'μg/m3'),
 (180, '潮州', '屏東縣', 20, datetime.datetime(2026, 4, 11, 22, 0), 'μg/m3'),
 (181, '屏東', '屏東縣', 24, datetime.datetime(2026, 4, 11, 22, 0), 'μg/m3'),
 (182, '小港', '高雄市', 20, datetime.datetime(2026, 4, 11, 22, 0), 'μg/m3'),
 (183, '前鎮', '高雄市', 16, datetime.datetime(2026, 4, 11, 22, 0), 'μg/m3'),
 (184, '前金', '高雄市', 21, datetime.datetime(2026, 4, 11, 22, 0), 'μg/m3'),
 (185, '左營', '高雄市', 18, datetime.datetime(2026, 4, 11, 22, 0), 'μg/m3'),
 (186, '楠梓', '高雄市', 23, datetime.datetime(2026, 4, 11, 22, 0), 'μg/m3'),
 (187, '林園', '高雄市', 16, datetime.datetime(2026, 4, 11, 22, 0), 'μg/m3'),
 (188, '大寮', '高雄市', 23, datetime.datetime(2026, 4, 11, 22, 0), 'μg/m3'),
 (189, '鳳山', '高雄市', 22, datetime.datetime(2026, 4, 11, 22, 0), 'μg/m3'),
 (190, '仁武', '高雄市', 18, datetime.datetime(2026, 4, 11, 22, 0), 'μg/m3'),
 (191, '橋頭', '高雄市', 21, datetime.datetime(2026, 4, 11, 22, 0), 'μg/m3'),
 (192, '美濃', '高雄市', 17, datetime.datetime(2026, 4, 11, 22, 0), 'μg/m3'),
 (193, '臺南', '臺南市', 18, datetime.datetime(2026, 4, 11, 22, 0), 'μg/m3'),
 (194, '安南', '臺南市', 18, datetime.datetime(2026, 4, 11, 22, 0), 'μg/m3'),
 (195, '善化', '臺南市', 28, datetime.datetime(2026, 4, 11, 22, 0), 'μg/m3'),
 (196, '新營', '臺南市', 21, datetime.datetime(2026, 4, 11, 22, 0), 'μg/m3'),
 (197, '嘉義', '嘉義市', 17, datetime.datetime(2026, 4, 11, 22, 0), 'μg/m3'),
 (198, '臺西', '雲林縣', 19, datetime.datetime(2026, 4, 11, 22, 0), 'μg/m3'),
 (199, '朴子', '嘉義縣', 20, datetime.datetime(2026, 4, 11, 22, 0), 'μg/m3'),
 (200, '新港', '嘉義縣', 19, datetime.datetime(2026, 4, 11, 22, 0), 'μg/m3'),
 (201, '崙背', '雲林縣', 23, datetime.datetime(2026, 4, 11, 22, 0), 'μg/m3'),
 (202, '斗六', '雲林縣', 18, datetime.datetime(2026, 4, 11, 22, 0), 'μg/m3'),
 (203, '南投', '南投縣', 24, datetime.datetime(2026, 4, 11, 22, 0), 'μg/m3'),
 (204, '二林', '彰化縣', 29, datetime.datetime(2026, 4, 11, 22, 0), 'μg/m3'),
 (205, '線西', '彰化縣', 25, datetime.datetime(2026, 4, 11, 22, 0), 'μg/m3'),
 (206, '彰化', '彰化縣', 20, datetime.datetime(2026, 4, 11, 22, 0), 'μg/m3'),
 (207, '西屯', '臺中市', 17, datetime.datetime(2026, 4, 11, 22, 0), 'μg/m3'),
 (208, '忠明', '臺中市', 24, datetime.datetime(2026, 4, 11, 22, 0), 'μg/m3'),
 (209, '大里', '臺中市', 19, datetime.datetime(2026, 4, 11, 22, 0), 'μg/m3'),
 (210, '沙鹿', '臺中市', 23, datetime.datetime(2026, 4, 11, 22, 0), 'μg/m3'),
 (211, '豐原', '臺中市', 20, datetime.datetime(2026, 4, 11, 22, 0), 'μg/m3'),
 (212, '三義', '苗栗縣', 21, datetime.datetime(2026, 4, 11, 22, 0), 'μg/m3'),
 (213, '苗栗', '苗栗縣', 24, datetime.datetime(2026, 4, 11, 22, 0), 'μg/m3'),
 (214, '頭份', '苗栗縣', 21, datetime.datetime(2026, 4, 11, 22, 0), 'μg/m3'),
 (215, '新竹', '新竹市', 18, datetime.datetime(2026, 4, 11, 22, 0), 'μg/m3'),
 (216, '竹東', '新竹縣', 21, datetime.datetime(2026, 4, 11, 22, 0), 'μg/m3'),
 (217, '湖口', '新竹縣', 17, datetime.datetime(2026, 4, 11, 22, 0), 'μg/m3'),
 (218, '龍潭', '桃園市', 24, datetime.datetime(2026, 4, 11, 22, 0), 'μg/m3'),
 (219, '平鎮', '桃園市', 17, datetime.datetime(2026, 4, 11, 22, 0), 'μg/m3'),
 (220, '觀音', '桃園市', 18, datetime.datetime(2026, 4, 11, 22, 0), 'μg/m3'),
 (221, '大園', '桃園市', 20, datetime.datetime(2026, 4, 11, 22, 0), 'μg/m3'),
 (222, '桃園', '桃園市', 24, datetime.datetime(2026, 4, 11, 22, 0), 'μg/m3'),
 (223, '大同', '臺北市', 23, datetime.datetime(2026, 4, 11, 22, 0), 'μg/m3'),
 (224, '松山', '臺北市', 18, datetime.datetime(2026, 4, 11, 22, 0), 'μg/m3'),
 (225, '古亭', '臺北市', 21, datetime.datetime(2026, 4, 11, 22, 0), 'μg/m3'),
 (226, '萬華', '臺北市', 26, datetime.datetime(2026, 4, 11, 22, 0), 'μg/m3'),
 (227, '中山', '臺北市', 24, datetime.datetime(2026, 4, 11, 22, 0), 'μg/m3'),
 (228, '士林', '臺北市', 20, datetime.datetime(2026, 4, 11, 22, 0), 'μg/m3'),
 (229, '淡水', '新北市', 14, datetime.datetime(2026, 4, 11, 22, 0), 'μg/m3'),
 (230, '林口', '新北市', 24, datetime.datetime(2026, 4, 11, 22, 0), 'μg/m3'),
 (231, '菜寮', '新北市', 20, datetime.datetime(2026, 4, 11, 22, 0), 'μg/m3'),
 (232, '新莊', '新北市', 24, datetime.datetime(2026, 4, 11, 22, 0), 'μg/m3'),
 (233, '板橋', '新北市', 21, datetime.datetime(2026, 4, 11, 22, 0), 'μg/m3'),
 (234, '土城', '新北市', 24, datetime.datetime(2026, 4, 11, 22, 0), 'μg/m3'),
 (235, '新店', '新北市', 27, datetime.datetime(2026, 4, 11, 22, 0), 'μg/m3'),
 (236, '汐止', '新北市', 21, datetime.datetime(2026, 4, 11, 22, 0), 'μg/m3'),
 (237, '基隆', '基隆市', 23, datetime.datetime(2026, 4, 11, 22, 0), 'μg/m3'),
 (238, '林森', '臺南市', 22, datetime.datetime(2026, 4, 11, 21, 0), 'μg/m3'),
 (239, '員林', '彰化縣', 21, datetime.datetime(2026, 4, 11, 21, 0), 'μg/m3'),
 (240, '臺灣大道', '臺中市', 21, datetime.datetime(2026, 4, 11, 21, 0), 'μg/m3'),
 (241, '大城', '彰化縣', 20, datetime.datetime(2026, 4, 11, 21, 0), 'μg/m3'),
 (242, '富貴角', '新北市', 22, datetime.datetime(2026, 4, 11, 21, 0), 'μg/m3'),
 (243, '麥寮', '雲林縣', 21, datetime.datetime(2026, 4, 11, 21, 0), 'μg/m3'),
 (244, '關山', '臺東縣', 20, datetime.datetime(2026, 4, 11, 21, 0), 'μg/m3'),
 (245, '金門', '金門縣', 15, datetime.datetime(2026, 4, 11, 21, 0), 'μg/m3'),
 (246, '馬祖', '連江縣', 26, datetime.datetime(2026, 4, 11, 21, 0), 'μg/m3'),
 (247, '埔里', '南投縣', 20, datetime.datetime(2026, 4, 11, 21, 0), 'μg/m3'),
 (248, '復興', '高雄市', 20, datetime.datetime(2026, 4, 11, 21, 0), 'μg/m3'),
 (249, '永和', '新北市', 20, datetime.datetime(2026, 4, 11, 21, 0), 'μg/m3'),
 (250, '竹山', '南投縣', 22, datetime.datetime(2026, 4, 11, 21, 0), 'μg/m3'),
 (251, '中壢', '桃園市', 21, datetime.datetime(2026, 4, 11, 21, 0), 'μg/m3'),
 (252, '三重', '新北市', 23, datetime.datetime(2026, 4, 11, 21, 0), 'μg/m3'),
 (253, '冬山', '宜蘭縣', 20, datetime.datetime(2026, 4, 11, 21, 0), 'μg/m3'),
 (254, '宜蘭', '宜蘭縣', 17, datetime.datetime(2026, 4, 11, 21, 0), 'μg/m3'),
 (255, '陽明', '臺北市', 18, datetime.datetime(2026, 4, 11, 21, 0), 'μg/m3'),
 (256, '花蓮', '花蓮縣', 18, datetime.datetime(2026, 4, 11, 21, 0), 'μg/m3'),
 (257, '臺東', '臺東縣', 24, datetime.datetime(2026, 4, 11, 21, 0), 'μg/m3'),
 (258, '恆春', '屏東縣', 15, datetime.datetime(2026, 4, 11, 21, 0), 'μg/m3'),
 (259, '潮州', '屏東縣', 21, datetime.datetime(2026, 4, 11, 21, 0), 'μg/m3'),
 (260, '屏東', '屏東縣', 26, datetime.datetime(2026, 4, 11, 21, 0), 'μg/m3'),
 (261, '小港', '高雄市', 23, datetime.datetime(2026, 4, 11, 21, 0), 'μg/m3'),
 (262, '前鎮', '高雄市', 20, datetime.datetime(2026, 4, 11, 21, 0), 'μg/m3'),
 (263, '前金', '高雄市', 13, datetime.datetime(2026, 4, 11, 21, 0), 'μg/m3'),
 (264, '左營', '高雄市', 16, datetime.datetime(2026, 4, 11, 21, 0), 'μg/m3'),
 (265, '楠梓', '高雄市', 18, datetime.datetime(2026, 4, 11, 21, 0), 'μg/m3'),
 (266, '林園', '高雄市', 18, datetime.datetime(2026, 4, 11, 21, 0), 'μg/m3'),
 (267, '大寮', '高雄市', 28, datetime.datetime(2026, 4, 11, 21, 0), 'μg/m3'),
 (268, '鳳山', '高雄市', 21, datetime.datetime(2026, 4, 11, 21, 0), 'μg/m3'),
 (269, '仁武', '高雄市', 18, datetime.datetime(2026, 4, 11, 21, 0), 'μg/m3'),
 (270, '橋頭', '高雄市', 19, datetime.datetime(2026, 4, 11, 21, 0), 'μg/m3'),
 (271, '美濃', '高雄市', 22, datetime.datetime(2026, 4, 11, 21, 0), 'μg/m3'),
 (272, '臺南', '臺南市', 19, datetime.datetime(2026, 4, 11, 21, 0), 'μg/m3'),
 (273, '安南', '臺南市', 21, datetime.datetime(2026, 4, 11, 21, 0), 'μg/m3'),
 (274, '善化', '臺南市', 19, datetime.datetime(2026, 4, 11, 21, 0), 'μg/m3'),
 (275, '新營', '臺南市', 23, datetime.datetime(2026, 4, 11, 21, 0), 'μg/m3'),
 (276, '嘉義', '嘉義市', 16, datetime.datetime(2026, 4, 11, 21, 0), 'μg/m3'),

In [37]:
df=pd.DataFrame(datas,columns=["id","site","county","pm25","datetime","itemunit"])
df

      id  site county  pm25            datetime itemunit
0      1    林森    臺南市    20 2026-04-12 00:00:00    μg/m3
1      2    員林    彰化縣    21 2026-04-12 00:00:00    μg/m3
2      3  臺灣大道    臺中市    23 2026-04-12 00:00:00    μg/m3
3      4    大城    彰化縣    23 2026-04-12 00:00:00    μg/m3
4      5   富貴角    新北市    16 2026-04-12 00:00:00    μg/m3
..   ...   ...    ...   ...                 ...      ...
989  990    臺南    臺南市    17 2026-04-11 12:00:00    μg/m3
990  991    安南    臺南市    19 2026-04-11 12:00:00    μg/m3
991  992    善化    臺南市    20 2026-04-11 12:00:00    μg/m3
992  993    新營    臺南市    20 2026-04-11 12:00:00    μg/m3
993  994    嘉義    嘉義市    15 2026-04-11 12:00:00    μg/m3

[994 rows x 6 columns]

In [38]:
df.groupby("county").get_group("新北市")

      id site county  pm25            datetime itemunit
4      5  富貴角    新北市    16 2026-04-12 00:00:00    μg/m3
11    12   永和    新北市    21 2026-04-12 00:00:00    μg/m3
14    15   三重    新北市    19 2026-04-12 00:00:00    μg/m3
70    71   淡水    新北市    23 2026-04-12 00:00:00    μg/m3
71    72   林口    新北市    23 2026-04-12 00:00:00    μg/m3
..   ...  ...    ...   ...                 ...      ...
951  952   新店    新北市    25 2026-04-11 13:00:00    μg/m3
952  953   汐止    新北市    26 2026-04-11 13:00:00    μg/m3
958  959  富貴角    新北市    15 2026-04-11 12:00:00    μg/m3
966  967   永和    新北市    23 2026-04-11 12:00:00    μg/m3
969  970   三重    新北市    26 2026-04-11 12:00:00    μg/m3

[135 rows x 6 columns]

In [40]:
df[["site","datetime"]].drop_duplicates()

     site            datetime
0      林森 2026-04-12 00:00:00
1      員林 2026-04-12 00:00:00
2    臺灣大道 2026-04-12 00:00:00
3      大城 2026-04-12 00:00:00
4     富貴角 2026-04-12 00:00:00
..    ...                 ...
989    臺南 2026-04-11 12:00:00
990    安南 2026-04-11 12:00:00
991    善化 2026-04-11 12:00:00
992    新營 2026-04-11 12:00:00
993    嘉義 2026-04-11 12:00:00

[994 rows x 2 columns]

### 取得各縣市站點的平均值

In [3]:
cursor.execute("select avg(pm25) from pm25;")
float(cursor.fetchone()[0])

19.0987

In [ ]:
sqlstr="""
select county,round(avg(pm25),2) from pm25 group by county;
"""

cursor.execute(sqlstr)
cursor.fetchall()

(('臺南市', Decimal('16.18')),
 ('彰化縣', Decimal('17.81')),
 ('臺中市', Decimal('16.91')),
 ('新北市', Decimal('21.03')),
 ('雲林縣', Decimal('17.39')),
 ('臺東縣', Decimal('18.29')),
 ('金門縣', Decimal('15.57')),
 ('連江縣', Decimal('25.64')),
 ('南投縣', Decimal('18.91')),
 ('高雄市', Decimal('17.84')),
 ('桃園市', Decimal('17.63')),
 ('宜蘭縣', Decimal('20.25')),
 ('臺北市', Decimal('20.13')),
 ('花蓮縣', Decimal('20.68')),
 ('屏東縣', Decimal('17.41')),
 ('嘉義市', Decimal('16.61')),
 ('嘉義縣', Decimal('16.30')),
 ('苗栗縣', Decimal('16.60')),
 ('新竹市', Decimal('14.19')),
 ('新竹縣', Decimal('17.13')),
 ('基隆市', Decimal('19.12')))

In [ ]:
df.groupby("county")["pm25"].mean()

In [10]:
cursor.execute("select avg(pm25) from pm25")
cursor.fetchone()[0]

Decimal('19.0987')

In [25]:
sqlstr="""
select county,round(avg(pm25),2) from pm25 group by county
"""
cursor.execute(sqlstr)
cursor.fetchall()

(('臺南市', Decimal('19.48')),
 ('彰化縣', Decimal('21.30')),
 ('臺中市', Decimal('19.27')),
 ('新北市', Decimal('18.42')),
 ('雲林縣', Decimal('22.90')),
 ('臺東縣', Decimal('17.99')),
 ('金門縣', Decimal('18.29')),
 ('連江縣', Decimal('23.78')),
 ('南投縣', Decimal('21.40')),
 ('高雄市', Decimal('19.35')),
 ('桃園市', Decimal('17.17')),
 ('宜蘭縣', Decimal('17.57')),
 ('臺北市', Decimal('17.79')),
 ('花蓮縣', Decimal('17.51')),
 ('屏東縣', Decimal('18.14')),
 ('嘉義市', Decimal('21.05')),
 ('嘉義縣', Decimal('22.19')),
 ('苗栗縣', Decimal('17.21')),
 ('新竹市', Decimal('15.53')),
 ('新竹縣', Decimal('18.07')),
 ('基隆市', Decimal('17.34')),
 ('澎湖縣', Decimal('16.69')))

In [27]:
conn.close()

### 取得單一縣市的站點數值

In [34]:
county="新北市"

#取得最新資料
sqlstr="""
select site,pm25,datacreationdate from pm25
where county=%s
and datacreationdate=(select max(datacreationdate) from pm25);
"""

cursor.execute(sqlstr,(county,))
cursor.fetchall()

(('富貴角', 18, datetime.datetime(2026, 4, 21, 3, 0)),
 ('永和', 10, datetime.datetime(2026, 4, 21, 3, 0)),
 ('三重', 14, datetime.datetime(2026, 4, 21, 3, 0)),
 ('淡水', 13, datetime.datetime(2026, 4, 21, 3, 0)),
 ('林口', 12, datetime.datetime(2026, 4, 21, 3, 0)),
 ('菜寮', 13, datetime.datetime(2026, 4, 21, 3, 0)),
 ('新莊', 13, datetime.datetime(2026, 4, 21, 3, 0)),
 ('板橋', 12, datetime.datetime(2026, 4, 21, 3, 0)),
 ('土城', 10, datetime.datetime(2026, 4, 21, 3, 0)),
 ('新店', 14, datetime.datetime(2026, 4, 21, 3, 0)),
 ('汐止', 16, datetime.datetime(2026, 4, 21, 3, 0)))